title: Advanced Physical Chemistry
description: A collection of course notes created by Fall 2025 CH730 (Advanced Physical Chemistry) students at NCSU.
remote_theme: pmarsceill/just-the-docs

enable_math: true

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
